myapp:
  properties:####endpoints_bts####
server:
  port: ####service_port####
info:
  version: "v1"
spring:
  application:
    name: ####service_name####
#Metricas de Actuator.
management:
    endpoint:
        health:
            show-details: 'always'
    endpoints:
        web:
            exposure:
                include: health,info,metrics
